<a href="https://colab.research.google.com/github/chevalier08/CST3390-Individual-Project/blob/main/EV_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Upload dataset

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving DATA.xlsx to DATA.xlsx

Import Pandas and Load data

In [ ]:
import pandas as pd

df = pd.read_excel("DATA.xlsx")

Initial Data Exploration

In [ ]:
df.head() #Displays the first 5 rows of the dataset

,date_and_time,power_demand_MWh,EV_fast_charging,EV_slow_charging,temperature(°C),humidity(%),ground_temperature(°C),is_holiday,day_type
0,2020.1.1 1:00,64007,3200,805,-5.2,53.7,-4.0,True,weekday
1,2020.1.1 2:00,61534,2320,791,-5.2,55.4,-3.9,True,weekday
2,2020.1.1 3:00,59447,1600,259,-5.1,57.1,-3.8,True,weekday
3,2020.1.1 4:00,58163,1520,84,-4.9,59.4,-3.5,True,weekday
4,2020.1.1 5:00,57884,2240,91,-4.3,61.1,-3.2,True,weekday

In [ ]:
df.tail() #Displays the last 5 rows of the dataset

,date_and_time,power_demand_MWh,EV_fast_charging,EV_slow_charging,temperature(°C),humidity(%),ground_temperature(°C),is_holiday,day_type
35035,2023.12.30 20:00,64934,10960,1883,4.3,87.8,3.4,False,weekend
35036,2023.12.30 21:00,63817,9600,1876,4.3,89.0,3.4,False,weekend
35037,2023.12.30 22:00,62436,8240,1813,4.4,89.2,3.4,False,weekend
35038,2023.12.30 23:00,63010,4960,1757,4.5,90.1,3.5,False,weekend
35039,2023.12.31 0:00,62981,4480,889,4.6,91.2,3.6,False,weekend

In [ ]:
df.info() #Provides a summary of the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35040 entries, 0 to 35039
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   date_and_time           35040 non-null  object
 1   power_demand_MWh        35040 non-null  int64
 2   EV_fast_charging        35040 non-null  int64
 3   EV_slow_charging        35040 non-null  int64
 4   temperature(°C)         34968 non-null  float64
 5   humidity(%)             34968 non-null  float64
 6   ground_temperature(°C)  34968 non-null  float64
 7   is_holiday              35040 non-null  bool
 8   day_type                35040 non-null  object
dtypes: bool(1), float64(3), int64(3), object(2)
memory usage: 2.2+ MB

In [ ]:
df.describe() #Generates descriptive statistics of the dataset

,power_demand_MWh,EV_fast_charging,EV_slow_charging,temperature(°C),humidity(%),ground_temperature(°C)
count,35040.000000,35040.000000,35040.000000,34968.000000,34968.000000,34968.000000
mean,63786.773830,11010.853881,1221.053910,13.544521,70.080891,15.640674
std,9397.286394,8064.906541,933.766863,9.792954,17.708243,11.798276
min,38422.000000,160.000000,14.000000,-15.100000,16.300000,-8.100000
25%,56853.000000,4040.000000,441.000000,5.700000,57.500000,5.500000
50%,62900.000000,9440.000000,1015.000000,14.400000,72.500000,15.900000
75%,69730.250000,16400.000000,1848.000000,22.000000,85.300000,24.600000
max,94509.000000,59040.000000,4662.000000,33.700000,98.000000,52.600000

Check for missing values

In [ ]:
df.isnull().sum()

date_and_time              0
power_demand_MWh           0
EV_fast_charging           0
EV_slow_charging           0
temperature(°C)           72
humidity(%)               72
ground_temperature(°C)    72
is_holiday                 0
day_type                   0
dtype: int64

In [ ]:
(df.isnull().sum() / len(df)) * 100

date_and_time             0.000000
power_demand_MWh          0.000000
EV_fast_charging          0.000000
EV_slow_charging          0.000000
temperature(°C)           0.205479
humidity(%)               0.205479
ground_temperature(°C)    0.205479
is_holiday                0.000000
day_type                  0.000000
dtype: float64

Data imputation

In [ ]:
df.columns

Index(['date_and_time', 'power_demand_MWh', 'EV_fast_charging',
       'EV_slow_charging', 'temperature(°C)', 'humidity(%)',
       'ground_temperature(°C)', 'is_holiday', 'day_type'],
      dtype='object')

In [ ]:
df['date_and_time'] = pd.to_datetime(df['date_and_time'])
df = df.set_index('date_and_time')
df[['temperature(°C)', 'ground_temperature(°C)', 'humidity(%)']] = \
df[['temperature(°C)', 'ground_temperature(°C)', 'humidity(%)']].interpolate(method='time') #Applying the interpolation method

In [ ]:
print(df.columns)

Index(['power_demand_MWh', 'EV_fast_charging', 'EV_slow_charging',
       'temperature(°C)', 'humidity(%)', 'ground_temperature(°C)',
       'is_holiday', 'day_type'],
      dtype='object')

In [ ]:
df.rename(columns={'date_and _time':'date_and_time'}, inplace=True)

In [ ]:
df.isnull().sum() #Checking sum of null values in each column

power_demand_MWh          0
EV_fast_charging          0
EV_slow_charging          0
temperature(°C)           0
humidity(%)               0
ground_temperature(°C)    0
is_holiday                0
day_type                  0
dtype: int64

In [ ]:
df = pd.get_dummies(df, columns=['day_type', 'is_holiday'], drop_first=True) #One-hot Encoding categorical variables

In [ ]:
df.head()

,power_demand_MWh,EV_fast_charging,EV_slow_charging,temperature(°C),humidity(%),ground_temperature(°C),day_type_weekend,is_holiday_True
date_and_time,,,,,,,,
2020-01-01 01:00:00,64007,3200,805,-5.2,53.7,-4.0,False,True
2020-01-01 02:00:00,61534,2320,791,-5.2,55.4,-3.9,False,True
2020-01-01 03:00:00,59447,1600,259,-5.1,57.1,-3.8,False,True
2020-01-01 04:00:00,58163,1520,84,-4.9,59.4,-3.5,False,True
2020-01-01 05:00:00,57884,2240,91,-4.3,61.1,-3.2,False,True

In [ ]:
df['day_type_weekend'] = df['day_type_weekend'].astype(int) #Converting from Boolean type to Integer type
df['is_holiday_True'] = df['is_holiday_True'].astype(int)

In [ ]:
df.head()

,power_demand_MWh,EV_fast_charging,EV_slow_charging,temperature(°C),humidity(%),ground_temperature(°C),day_type_weekend,is_holiday_True
date_and_time,,,,,,,,
2020-01-01 01:00:00,64007,3200,805,-5.2,53.7,-4.0,0,1
2020-01-01 02:00:00,61534,2320,791,-5.2,55.4,-3.9,0,1
2020-01-01 03:00:00,59447,1600,259,-5.1,57.1,-3.8,0,1
2020-01-01 04:00:00,58163,1520,84,-4.9,59.4,-3.5,0,1
2020-01-01 05:00:00,57884,2240,91,-4.3,61.1,-3.2,0,1

In [ ]:
df.tail()

,power_demand_MWh,EV_fast_charging,EV_slow_charging,temperature(°C),humidity(%),ground_temperature(°C),day_type_weekend,is_holiday_True
date_and_time,,,,,,,,
2023-12-30 20:00:00,64934,10960,1883,4.3,87.8,3.4,1,0
2023-12-30 21:00:00,63817,9600,1876,4.3,89.0,3.4,1,0
2023-12-30 22:00:00,62436,8240,1813,4.4,89.2,3.4,1,0
2023-12-30 23:00:00,63010,4960,1757,4.5,90.1,3.5,1,0
2023-12-31 00:00:00,62981,4480,889,4.6,91.2,3.6,1,0

The ADF test - To check for stationarity

In [ ]:
from statsmodels.tsa.stattools import adfuller

result = adfuller(df['power_demand_MWh'])

print("p-value:", result[1])

p-value: 2.4739935924598156e-28

In [ ]:
df = df.rename(columns={ #Renaming columns
    'power_demand(MWh)': 'power_demand_MWh',
    'temperature(°C)': 'temperature_c',
    'ground_temperature(°C)': 'ground_temperature_c',
    'humidity(%)': 'humidity_pct'
})

In [ ]:
df.columns

Index(['power_demand_MWh', 'EV_fast_charging', 'EV_slow_charging',
       'temperature_c', 'humidity_pct', 'ground_temperature_c',
       'day_type_weekend', 'is_holiday_True'],
      dtype='object')

SARIMAX Modelling

Scenario A -- Without EV Charging

In [ ]:
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

y = df['power_demand_MWh'] #Defining target variable

X_noEV = df.drop(columns=[ #Excluding EV charging variables
    'power_demand_MWh',
    'EV_fast_charging',
    'EV_slow_charging'
])

train_size = int(len(df) * 0.8) #80% training size

# Target
y_train = y.iloc[:train_size]
y_test  = y.iloc[train_size:]

# Without EV
X_train_noEV = X_noEV.iloc[:train_size]
X_test_noEV  = X_noEV.iloc[train_size:]


# Model 1: Without EV
model_noEV = SARIMAX(y_train,
                     exog=X_train_noEV,
                     order=(1,0,1),
                     seasonal_order=(1,0,1,24),
                     enforce_stationarity=False,
                     enforce_invertibility=False)

results_noEV = model_noEV.fit()

forecast_noEV = results_noEV.predict(start=len(y_train),
                                     end=len(y_train)+len(y_test)-1,
                                     exog=X_test_noEV)

mae_noEV = mean_absolute_error(y_test, forecast_noEV)
accuracy_noEV = 100 * (1 - mae_noEV / y_test.mean())
rmse_noEV = np.sqrt(mean_squared_error(y_test, forecast_noEV))
mape_noEV = np.mean(np.abs((y_test - forecast_noEV) / y_test)) * 100

print("Without EV - Accuracy: {:.2f}%".format(accuracy_noEV))
print("Without EV - MAE:", mae_noEV)
print("Without EV - RMSE:", rmse_noEV)
print("Without EV - MAPE: {:.2f}%".format(mape_noEV))

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency h will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency h will be used.
  self._init_dates(dates, freq)

Without EV - Accuracy: 79.85%
Without EV - MAE: 12844.93375068533
Without EV - RMSE: 15270.556675404932
Without EV - MAPE: 21.25%

Scenario B -- With EV Charging

In [ ]:
X_withEV = df.drop(columns=['power_demand_MWh'])
train_size = int(len(df) * 0.8)

# Target
y_train = y.iloc[:train_size]
y_test  = y.iloc[train_size:]

# With EV
X_train_withEV = X_withEV.iloc[:train_size]
X_test_withEV  = X_withEV.iloc[train_size:]

from statsmodels.tsa.statespace.sarimax import SARIMAX
model_withEV = SARIMAX(y_train,
                       exog=X_train_withEV,
                       order=(1,0,1),
                       seasonal_order=(1,0,1,24),
                       enforce_stationarity=False,
                       enforce_invertibility=False)

results_withEV = model_withEV.fit()

forecast_withEV = results_withEV.predict(start=len(y_train),
                                         end=len(y_train)+len(y_test)-1,
                                         exog=X_test_withEV)

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae_withEV = mean_absolute_error(y_test, forecast_withEV)
accuracy_withEV = 100 * (1 - mae_withEV / y_test.mean())
rmse_withEV = np.sqrt(mean_squared_error(y_test, forecast_withEV))
mape_withEV = np.mean(np.abs((y_test - forecast_withEV) / y_test)) * 100

print("With EV - Accuracy: {:.2f}%".format(accuracy_withEV))
print("With EV - MAE:", mae_withEV)
print("With EV - RMSE:", rmse_withEV)
print("With EV - MAPE: {:.2f}%".format(mape_withEV))

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency h will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency h will be used.
  self._init_dates(dates, freq)

With EV - Accuracy: 87.05%
With EV - MAE: 8254.700083501732
With EV - RMSE: 10277.556413848262
With EV - MAPE: 13.23%

SVR - Scenario A - Without EV

In [ ]:
import numpy as np
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error


# Scenario A: WITHOUT EV variables

X = df.drop(columns=['power_demand_MWh', 'EV_fast_charging', 'EV_slow_charging'])
y = df['power_demand_MWh']

split = int(len(df) * 0.8)

X_train = X[:split]
X_test = X[split:]

y_train = y[:split]
y_test = y[split:]

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

svr = SVR(kernel='rbf')
svr.fit(X_train_scaled, y_train)

pred = svr.predict(X_test_scaled)

mae = mean_absolute_error(y_test, pred)
rmse = np.sqrt(mean_squared_error(y_test, pred))
mape = np.mean(np.abs((y_test - pred) / y_test)) * 100
accuracy = 100 * (1 - mae / y_test.mean())

print("SVR WITHOUT EV")
print("MAE:", mae)
print("RMSE:", rmse)
print("MAPE:", mape)
print("Accuracy:", accuracy)

SVR WITHOUT EV
MAE: 7077.789129274904
RMSE: 8999.740248683163
MAPE: 11.089864249590663
Accuracy: 88.8956800295282

SVR - Scenario B - With EV

In [ ]:
import numpy as np
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Scenario B: WITH EV variables

X = df.drop(columns=['power_demand_MWh'])

X_train = X[:split]
X_test = X[split:]

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

svr = SVR(kernel='rbf')
svr.fit(X_train_scaled, y_train)

pred = svr.predict(X_test_scaled)

mae = mean_absolute_error(y_test, pred)
rmse = np.sqrt(mean_squared_error(y_test, pred))
mape = np.mean(np.abs((y_test - pred) / y_test)) * 100
accuracy = 100 * (1 - mae / y_test.mean())

print("SVR WITH EV")
print("MAE:", mae)
print("RMSE:", rmse)
print("MAPE:", mape)
print("Accuracy:", accuracy)

SVR WITH EV
MAE: 6736.878926112385
RMSE: 8677.219718596816
MAPE: 10.623836025285632
Accuracy: 89.43053292044823